export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/",
  MEMBERS: "/members",
  MEMBER_DETAIL: (id: string) => `/members/${id}`,
  MEMBER_NEW: "/members/new",
  MEMBER_EDIT: (id: string) => `/members/${id}/edit`,
  MEMBERSHIPS: "/memberships",
  MEMBERSHIP_DETAIL: (id: string) => `/memberships/${id}`,
  PAYMENTS: "/payments",
  PAYMENT_DETAIL: (id: string) => `/payments/${id}`,
  PAYMENT_NEW: "/payments/new",
  PAYMENT_EDIT: (id: string) => `/payments/${id}/edit`,
  EXPENSES: "/expenses",
  EXPENSE_DETAIL: (id: string) => `/expenses/${id}`,
  EXPENSE_NEW: "/expenses/new",
  EXPENSE_EDIT: (id: string) => `/expenses/${id}/edit`,
  REPORTS: "/reports",
  REPORT_REVENUE: "/reports/revenue",
  REPORT_EXPENSES: "/reports/expenses",
  REPORT_PROFIT: "/reports/profit",
  REPORT_MEMBERSHIPS: "/reports/memberships",
  REPORT_OUTSTANDING: "/reports/outstanding",
  SETTINGS: "/settings",
  SETTINGS_PROFILE: "/settings/profile",
  SETTINGS_USERS: "/settings/users",
  SETTINGS_PLANS: "/settings/plans",
  SETTINGS_CATEGORIES: "/settings/categories",
  SETTINGS_AUTOMATION: "/settings/automation",
  SETTINGS_EXPORTS: "/settings/exports",
  SETTINGS_SYSTEM: "/settings/system",
  SETTINGS_TEMPLATES: "/settings/templates",
  SETTINGS_SCHEDULED: "/settings/scheduled",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  LEADS: "/leads",
} as const;

export const STATUS_COLORS = {
  active: "bg-green-100 text-green-800",
  expired: "bg-red-100 text-red-800",
  frozen: "bg-blue-100 text-blue-800",
  inactive: "bg-gray-100 text-gray-800",
  cancelled: "bg-orange-100 text-orange-800",
  paid: "bg-green-100 text-green-800",
  partial: "bg-yellow-100 text-yellow-800",
  pending: "bg-orange-100 text-orange-800",
  refunded: "bg-purple-100 text-purple-800",
  draft: "bg-gray-100 text-gray-800",
  scheduled: "bg-blue-100 text-blue-800",
  sent: "bg-green-100 text-green-800",
  failed: "bg-red-100 text-red-800",
} as const;
